### ISSUE TITLE
lovelace-card-templater disappears/reappears from Tracker Card when clicking "Check"

### ISSUE THREAD

**Issue by mrsnyds** [gadgetchnnel/lovelace-card-templater#1]
I think this card is great, by the way, and welcome back. 

I am not certain this is a bug, but I believe I have followed all the documentation correctly for the [Custom Updater and Tracker Card](https://github.com/custom-cards/tracker-card).  In case you are able to duplicate it, wanted you to know about it.

I have this entry in the resources section of my Lovelace raw config:
```
  - type: js
    url: /customcards/github/gadgetchnnel/lovelace-card-templater.js?track=true
```
I am running the latest 0.93.1 version of HASSIO on an RP3 and the javascript resides here:
`config/www/github/gadgetchnnel/lovelace-card-templater.js`

The behavior I'm seeing is the alternating appearance and disappearance of the card templater card entry when I click the "Check" button, as shown in this screen shot.

![update](https://user-images.githubusercontent.com/41122989/58169313-6f71a680-7c5e-11e9-8185-de48831cb2b8.png)

**Comment by gadgetchnnel** [comment]
As I understand it, this was a limitation due to the way custom_updater handled "super custom cards" (using the ?track=true option). This card now fully supports [HACS](https://github.com/custom-components/hacs) (the replacement for custom_updater) which doesn't have this same issue.
