### ISSUE TITLE
User level error

### ISSUE THREAD

**Issue by jscott304** [gadgetchnnel/lovelace-card-templater#11]
For the templates to work the user needs to be set as an administrator. If they are set to a user it simply displays as Error!

**Comment by gadgetchnnel** [comment]
I have refactored template processing in the latest beta version (0.0.8b1) which I believe will allow this to work for non-admins. Can you give it a go and let me know if this works for you?

**Comment by J-Lindvig** [comment]
Thank you for your work.
I experience the issue issue and unfortunately v.(0.0.8b1) does not fix it,
I have made a code sample which will fail if the user is not admin

- type: custom:card-templater
  entities:
    - input_select.movie
  card:
    type: picture
    image_template: >-
      {% set test_image = "https://cdn.pixabay.com/photo/2018/01/16/10/36/mistake-3085712_960_720.jpg" %}
      {{ test_image }}

**Comment by gadgetchnnel** [comment]
@J-Lindvig Can you check if you get any errors in the JavaScript console in the web browser?

**Comment by J-Lindvig** [comment]
Morning....

Hope the attached log is helpfull - if not please respond.

/Jacob


Citat af Steven Rollason <notifications@github.com>:

> @J-Lindvig Can you check if you get any errors in the JavaScript  
> console in the web browser?
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/gadgetchnnel/lovelace-card-templater/issues/11#issuecomment-586755525



bar-card.js:1 BAR-CARDVersion: 1.7.1
custom-header.js:145   CUSTOM-HEADER    Version 1.3.2  
card-tools.js:1 CARD-TOOLS 2 IS INSTALLED  DeviceID: 527754cd-95c8b201
fetch-with-auth.ts:20 POST https://ha.skovtrolden.duckdns.org/api/template 401
r @ fetch-with-auth.ts:20
o @ hass-call-api.ts:67
callApi @ connection-mixin.ts:86
applyTemplate @ lovelace-card-templater.js:192
getCardConfig @ lovelace-card-templater.js:264
set hass @ lovelace-card-templater.js:142
build_card @ layout-card.js:1
(anonymous) @ layout-card.js:1
build_cards @ layout-card.js:1
updated @ layout-card.js:1
performUpdate @ updating-element.ts:720
_enqueueUpdate @ updating-element.ts:653
async function (async)
_enqueueUpdate @ updating-element.ts:640
_requestUpdate @ updating-element.ts:605
initialize @ updating-element.ts:449
initialize @ lit-element.ts:146
O @ updating-element.ts:438
V @ lit-element.ts:61
(anonymous) @ layout-card.js:1
o @ create-element-base.ts:34
a @ create-element-base.ts:79
bn @ create-card-element.ts:57
value @ hui-panel-view.ts:55
value @ hui-panel-view.ts:34
performUpdate @ updating-element.ts:704
_enqueueUpdate @ updating-element.ts:653
async function (async)
_enqueueUpdate @ updating-element.ts:640
_requestUpdate @ updating-element.ts:605
initialize @ updating-element.ts:449
O @ updating-element.ts:438
r @ hui-panel-view.ts:16
value @ hui-root.ts:697
(anonymous) @ hui-root.ts:77
(anonymous) @ debounce.ts:22
setTimeout (async)
(anonymous) @ debounce.ts:27
handleEvent @ parts.ts:505
__boundHandleEvent @ parts.ts:463
p @ auto-entities.js:1
(anonymous) @ auto-entities.js:2
i @ auto-entities.js:1
(anonymous) @ auto-entities.js:1
(anonymous) @ auto-entities.js:1
lovelace-card-templater.js:196 Error parsing template.
applyTemplate @ lovelace-card-templater.js:196
async function (async)
applyTemplate @ lovelace-card-templater.js:192
getCardConfig @ lovelace-card-templater.js:264
set hass @ lovelace-card-templater.js:142
build_card @ layout-card.js:1
(anonymous) @ layout-card.js:1
build_cards @ layout-card.js:1
updated @ layout-card.js:1
performUpdate @ updating-element.ts:720
_enqueueUpdate @ updating-element.ts:653
async function (async)
_enqueueUpdate @ updating-element.ts:640
_requestUpdate @ updating-element.ts:605
initialize @ updating-element.ts:449
initialize @ lit-element.ts:146
O @ updating-element.ts:438
V @ lit-element.ts:61
(anonymous) @ layout-card.js:1
o @ create-element-base.ts:34
a @ create-element-base.ts:79
bn @ create-card-element.ts:57
value @ hui-panel-view.ts:55
value @ hui-panel-view.ts:34
performUpdate @ updating-element.ts:704
_enqueueUpdate @ updating-element.ts:653
async function (async)
_enqueueUpdate @ updating-element.ts:640
_requestUpdate @ updating-element.ts:605
initialize @ updating-element.ts:449
O @ updating-element.ts:438
r @ hui-panel-view.ts:16
value @ hui-root.ts:697
(anonymous) @ hui-root.ts:77
(anonymous) @ debounce.ts:22
setTimeout (async)
(anonymous) @ debounce.ts:27
handleEvent @ parts.ts:505
__boundHandleEvent @ parts.ts:463
p @ auto-entities.js:1
(anonymous) @ auto-entities.js:2
i @ auto-entities.js:1
(anonymous) @ auto-entities.js:1
(anonymous) @ auto-entities.js:1
Error!:1 GET https://ha.skovtrolden.duckdns.org/Error! 404
Image (async)
commit @ parts.ts:96
commit @ parts.ts:133
update @ template-instance.ts:53
__commitTemplateResult @ parts.ts:277
commit @ parts.ts:218
s @ render.ts:55
V.render @ shady-render.ts:277
update @ lit-element.ts:220
performUpdate @ updating-element.ts:704
_enqueueUpdate @ updating-element.ts:653
async function (async)
_enqueueUpdate @ updating-element.ts:640
_requestUpdate @ updating-element.ts:605
set @ updating-element.ts:313
value @ hui-picture-card.ts:55
(anonymous) @ lovelace-card-templater.js:163
Promise.then (async)
(anonymous) @ lovelace-card-templater.js:161
Promise.then (async)
set hass @ lovelace-card-templater.js:142
build_card @ layout-card.js:1
(anonymous) @ layout-card.js:1
build_cards @ layout-card.js:1
updated @ layout-card.js:1
performUpdate @ updating-element.ts:720
_enqueueUpdate @ updating-element.ts:653
async function (async)
_enqueueUpdate @ updating-element.ts:640
_requestUpdate @ updating-element.ts:605
initialize @ updating-element.ts:449
initialize @ lit-element.ts:146
O @ updating-element.ts:438
V @ lit-element.ts:61
(anonymous) @ layout-card.js:1
o @ create-element-base.ts:34
a @ create-element-base.ts:79
bn @ create-card-element.ts:57
value @ hui-panel-view.ts:55
value @ hui-panel-view.ts:34
performUpdate @ updating-element.ts:704
_enqueueUpdate @ updating-element.ts:653
async function (async)
_enqueueUpdate @ updating-element.ts:640
_requestUpdate @ updating-element.ts:605
initialize @ updating-element.ts:449
O @ updating-element.ts:438
r @ hui-panel-view.ts:16
value @ hui-root.ts:697
(anonymous) @ hui-root.ts:77
(anonymous) @ debounce.ts:22
setTimeout (async)
(anonymous) @ debounce.ts:27
handleEvent @ parts.ts:505
__boundHandleEvent @ parts.ts:463
p @ auto-entities.js:1
(anonymous) @ auto-entities.js:2
i @ auto-entities.js:1
(anonymous) @ auto-entities.js:1
(anonymous) @ auto-entities.js:1
slider-entity-row.js:20 Uncaught (in promise) TypeError: Cannot read property 'state' of null
    at HTMLElement.render (slider-entity-row.js:20)
    at HTMLElement.update (lit-element.ts:217)
    at HTMLElement.performUpdate (updating-element.ts:704)
    at HTMLElement._enqueueUpdate (updating-element.ts:653)
render @ slider-entity-row.js:20
update @ lit-element.ts:217
performUpdate @ updating-element.ts:704
_enqueueUpdate @ updating-element.ts:653
Promise.then (async)
(anonymous) @ vertical-stack-in-card.js:122
connectedCallback @ vertical-stack-in-card.js:116
V.render @ shady-render.ts:305
update @ lit-element.ts:220
performUpdate @ updating-element.ts:704
_enqueueUpdate @ updating-element.ts:653
async function (async)
_enqueueUpdate @ updating-element.ts:640
_requestUpdate @ updating-element.ts:605
initialize @ updating-element.ts:449
initialize @ lit-element.ts:146
O @ updating-element.ts:438
V @ lit-element.ts:61
(anonymous) @ state-switch.js:1
_createThing @ vertical-stack-in-card.js:25
(anonymous) @ vertical-stack-in-card.js:78
setConfig @ vertical-stack-in-card.js:66
(anonymous) @ layout-card.js:1
l @ layout-card.js:1
u @ layout-card.js:1
build_card @ layout-card.js:1
(anonymous) @ layout-card.js:1
build_cards @ layout-card.js:1
updated @ layout-card.js:1
performUpdate @ updating-element.ts:720
_enqueueUpdate @ updating-element.ts:653
async function (async)
_enqueueUpdate @ updating-element.ts:640
_requestUpdate @ updating-element.ts:605
initialize @ updating-element.ts:449
initialize @ lit-element.ts:146
O @ updating-element.ts:438
V @ lit-element.ts:61
(anonymous) @ layout-card.js:1
o @ create-element-base.ts:34
a @ create-element-base.ts:79
bn @ create-card-element.ts:57
value @ hui-panel-view.ts:55
value @ hui-panel-view.ts:34
performUpdate @ updating-element.ts:704
_enqueueUpdate @ updating-element.ts:653
async function (async)
_enqueueUpdate @ updating-element.ts:640
_requestUpdate @ updating-element.ts:605
initialize @ updating-element.ts:449
O @ updating-element.ts:438
r @ hui-panel-view.ts:16
value @ hui-root.ts:697
(anonymous) @ hui-root.ts:534
setTimeout (async)
(anonymous) @ render-status.ts:2
(anonymous) @ timeline.js:21
requestAnimationFrame (async)
(anonymous) @ timeline.js:19
i @ render-status.ts:2
value @ hui-root.ts:534
performUpdate @ updating-element.ts:720
_enqueueUpdate @ updating-element.ts:653
async function (async)
_enqueueUpdate @ updating-element.ts:640
_requestUpdate @ updating-element.ts:605
set @ updating-element.ts:313
commit @ parts.ts:420
commit @ parts.ts:133
update @ template-instance.ts:53
__commitTemplateResult @ parts.ts:268
commit @ parts.ts:218
s @ render.ts:55
V.render @ shady-render.ts:277
update @ lit-element.ts:220
performUpdate @ updating-element.ts:704
_enqueueUpdate @ updating-element.ts:653
async function (async)
_enqueueUpdate @ updating-element.ts:640
_requestUpdate @ updating-element.ts:605
set @ updating-element.ts:313
value @ partial-panel-resolver.ts:134
value @ hass-router-page.ts:128
performUpdate @ updating-element.ts:704
_enqueueUpdate @ updating-element.ts:653
async function (async)
_enqueueUpdate @ updating-element.ts:640
_requestUpdate @ updating-element.ts:605
set @ updating-element.ts:313
commit @ parts.ts:420
commit @ parts.ts:133
update @ template-instance.ts:53
__commitTemplateResult @ parts.ts:268
commit @ parts.ts:218
s @ render.ts:55
V.render @ shady-render.ts:277
update @ lit-element.ts:220
performUpdate @ updating-element.ts:704
_enqueueUpdate @ updating-element.ts:653
async function (async)
_enqueueUpdate @ updating-element.ts:640
_requestUpdate @ updating-element.ts:605
set @ updating-element.ts:313
commit @ parts.ts:420
commit @ parts.ts:133
update @ template-instance.ts:53
__commitTemplateResult @ parts.ts:268
commit @ parts.ts:218
update @ template-instance.ts:53
__commitTemplateResult @ parts.ts:268
commit @ parts.ts:218
s @ render.ts:55
V.render @ shady-render.ts:277
update @ lit-element.ts:220
performUpdate @ updating-element.ts:704
_enqueueUpdate @ updating-element.ts:653
async function (async)
_enqueueUpdate @ updating-element.ts:640
_requestUpdate @ updating-element.ts:605
set @ updating-element.ts:313
value @ home-assistant.ts:93
async function (async)
value @ home-assistant.ts:80
handleEvent @ parts.ts:505
__boundHandleEvent @ parts.ts:463
j @ property-effects.js:299
C @ property-effects.js:324
w @ property-effects.js:155
(anonymous) @ property-effects.js:242
_propertiesChanged @ property-effects.js:1657
_flushProperties @ properties-changed.js:352
_flushProperties @ property-effects.js:1502
_invalidateProperties @ property-effects.js:1474
_setProperty @ property-effects.js:1459
Object.defineProperty.set @ properties-changed.js:152
_locationChanged @ app-route-converter-behavior.js:78
I @ property-effects.js:811
w @ property-effects.js:155
v @ property-effects.js:121
_propertiesChanged @ property-effects.js:1654
_flushProperties @ properties-changed.js:352
_flushProperties @ property-effects.js:1502
_invalidateProperties @ property-effects.js:1474
_setProperty @ property-effects.js:1459
Object.defineProperty.set @ properties-changed.js:152
__computeRoutePath @ app-location.js:194
I @ property-effects.js:811
w @ property-effects.js:155
v @ property-effects.js:121
_propertiesChanged @ property-effects.js:1654
_flushProperties @ properties-changed.js:352
_flushProperties @ property-effects.js:1502
_invalidateProperties @ property-effects.js:1474
(anonymous) @ property-effects.js:254
_propertiesChanged @ property-effects.js:1657
_flushProperties @ properties-changed.js:352
_flushProperties @ property-effects.js:1502
_invalidateProperties @ property-effects.js:1474
_setProperty @ property-effects.js:1459
Object.defineProperty.set @ properties-changed.js:152
_urlChanged @ iron-location.js:185
(anonymous) @ template-stamp.js:87
l @ browser_mod.js:1
navigate @ browser_mod.js:56
callback @ browser_mod.js:56
e.subscribeMessage.type @ browser_mod.js:56
c._handleMessage @ connection.ts:254
(anonymous) @ connection.ts:100
Show 46 more frames
slider-entity-row.js:20 Uncaught (in promise) TypeError: Cannot read property 'state' of null
    at HTMLElement.render (slider-entity-row.js:20)
    at HTMLElement.update (lit-element.ts:217)
    at HTMLElement.performUpdate (updating-element.ts:704)
    at HTMLElement._enqueueUpdate (updating-element.ts:653)
render @ slider-entity-row.js:20
update @ lit-element.ts:217
performUpdate @ updating-element.ts:704
_enqueueUpdate @ updating-element.ts:653
Promise.then (async)
(anonymous) @ vertical-stack-in-card.js:122
connectedCallback @ vertical-stack-in-card.js:116
__insert @ parts.ts:233
__commitNode @ parts.ts:241
__commitTemplateResult @ parts.ts:278
commit @ parts.ts:218
__commitIterable @ parts.ts:320
commit @ parts.ts:222
update @ template-instance.ts:53
__commitTemplateResult @ parts.ts:268
commit @ parts.ts:218
s @ render.ts:55
V.render @ shady-render.ts:277
update @ lit-element.ts:220
performUpdate @ updating-element.ts:704
_enqueueUpdate @ updating-element.ts:653
async function (async)
_enqueueUpdate @ updating-element.ts:640
_requestUpdate @ updating-element.ts:605
requestUpdate @ updating-element.ts:623
place_cards @ layout-card.js:1
updated @ layout-card.js:1
async function (async)
updated @ layout-card.js:1
performUpdate @ updating-element.ts:720
_enqueueUpdate @ updating-element.ts:653
async function (async)
_enqueueUpdate @ updating-element.ts:640
_requestUpdate @ updating-element.ts:605
initialize @ updating-element.ts:449
initialize @ lit-element.ts:146
O @ updating-element.ts:438
V @ lit-element.ts:61
(anonymous) @ layout-card.js:1
o @ create-element-base.ts:34
a @ create-element-base.ts:79
bn @ create-card-element.ts:57
value @ hui-panel-view.ts:55
value @ hui-panel-view.ts:34
performUpdate @ updating-element.ts:704
_enqueueUpdate @ updating-element.ts:653
async function (async)
_enqueueUpdate @ updating-element.ts:640
_requestUpdate @ updating-element.ts:605
initialize @ updating-element.ts:449
O @ updating-element.ts:438
r @ hui-panel-view.ts:16
value @ hui-root.ts:697
(anonymous) @ hui-root.ts:534
setTimeout (async)
(anonymous) @ render-status.ts:2
(anonymous) @ timeline.js:21
requestAnimationFrame (async)
(anonymous) @ timeline.js:19
i @ render-status.ts:2
value @ hui-root.ts:534
performUpdate @ updating-element.ts:720
_enqueueUpdate @ updating-element.ts:653
async function (async)
_enqueueUpdate @ updating-element.ts:640
_requestUpdate @ updating-element.ts:605
set @ updating-element.ts:313
commit @ parts.ts:420
commit @ parts.ts:133
update @ template-instance.ts:53
__commitTemplateResult @ parts.ts:268
commit @ parts.ts:218
s @ render.ts:55
V.render @ shady-render.ts:277
update @ lit-element.ts:220
performUpdate @ updating-element.ts:704
_enqueueUpdate @ updating-element.ts:653
async function (async)
_enqueueUpdate @ updating-element.ts:640
_requestUpdate @ updating-element.ts:605
set @ updating-element.ts:313
value @ partial-panel-resolver.ts:134
value @ hass-router-page.ts:128
performUpdate @ updating-element.ts:704
_enqueueUpdate @ updating-element.ts:653
async function (async)
_enqueueUpdate @ updating-element.ts:640
_requestUpdate @ updating-element.ts:605
set @ updating-element.ts:313
commit @ parts.ts:420
commit @ parts.ts:133
update @ template-instance.ts:53
__commitTemplateResult @ parts.ts:268
commit @ parts.ts:218
s @ render.ts:55
V.render @ shady-render.ts:277
update @ lit-element.ts:220
performUpdate @ updating-element.ts:704
_enqueueUpdate @ updating-element.ts:653
async function (async)
_enqueueUpdate @ updating-element.ts:640
_requestUpdate @ updating-element.ts:605
set @ updating-element.ts:313
commit @ parts.ts:420
commit @ parts.ts:133
update @ template-instance.ts:53
__commitTemplateResult @ parts.ts:268
commit @ parts.ts:218
update @ template-instance.ts:53
__commitTemplateResult @ parts.ts:268
commit @ parts.ts:218
s @ render.ts:55
V.render @ shady-render.ts:277
update @ lit-element.ts:220
performUpdate @ updating-element.ts:704
_enqueueUpdate @ updating-element.ts:653
async function (async)
_enqueueUpdate @ updating-element.ts:640
_requestUpdate @ updating-element.ts:605
set @ updating-element.ts:313
value @ home-assistant.ts:93
async function (async)
value @ home-assistant.ts:80
handleEvent @ parts.ts:505
__boundHandleEvent @ parts.ts:463
j @ property-effects.js:299
C @ property-effects.js:324
w @ property-effects.js:155
(anonymous) @ property-effects.js:242
_propertiesChanged @ property-effects.js:1657
_flushProperties @ properties-changed.js:352
_flushProperties @ property-effects.js:1502
_invalidateProperties @ property-effects.js:1474
_setProperty @ property-effects.js:1459
Object.defineProperty.set @ properties-changed.js:152
_locationChanged @ app-route-converter-behavior.js:78
I @ property-effects.js:811
w @ property-effects.js:155
v @ property-effects.js:121
_propertiesChanged @ property-effects.js:1654
_flushProperties @ properties-changed.js:352
_flushProperties @ property-effects.js:1502
_invalidateProperties @ property-effects.js:1474
_setProperty @ property-effects.js:1459
Object.defineProperty.set @ properties-changed.js:152
__computeRoutePath @ app-location.js:194
I @ property-effects.js:811
w @ property-effects.js:155
v @ property-effects.js:121
_propertiesChanged @ property-effects.js:1654
_flushProperties @ properties-changed.js:352
_flushProperties @ property-effects.js:1502
_invalidateProperties @ property-effects.js:1474
(anonymous) @ property-effects.js:254
_propertiesChanged @ property-effects.js:1657
_flushProperties @ properties-changed.js:352
_flushProperties @ property-effects.js:1502
_invalidateProperties @ property-effects.js:1474
_setProperty @ property-effects.js:1459
Object.defineProperty.set @ properties-changed.js:152
_urlChanged @ iron-location.js:185
(anonymous) @ template-stamp.js:87
l @ browser_mod.js:1
navigate @ browser_mod.js:56
callback @ browser_mod.js:56
e.subscribeMessage.type @ browser_mod.js:56
c._handleMessage @ connection.ts:254
(anonymous) @ connection.ts:100
Show 46 more frames
slider-entity-row.js:20 Uncaught (in promise) TypeError: Cannot read property 'state' of null
    at HTMLElement.render (slider-entity-row.js:20)
    at HTMLElement.update (lit-element.ts:217)
    at HTMLElement.performUpdate (updating-element.ts:704)
    at HTMLElement._enqueueUpdate (updating-element.ts:653)
render @ slider-entity-row.js:20
update @ lit-element.ts:217
performUpdate @ updating-element.ts:704
_enqueueUpdate @ updating-element.ts:653
async function (async)
_enqueueUpdate @ updating-element.ts:640
_requestUpdate @ updating-element.ts:605
set @ updating-element.ts:313
(anonymous) @ vertical-stack-in-card.js:110
set hass @ vertical-stack-in-card.js:109
updated @ state-switch.js:1
performUpdate @ updating-element.ts:720
_enqueueUpdate @ updating-element.ts:653
async function (async)
_enqueueUpdate @ updating-element.ts:640
_requestUpdate @ updating-element.ts:605
set @ updating-element.ts:313
(anonymous) @ vertical-stack-in-card.js:110
set hass @ vertical-stack-in-card.js:109
(anonymous) @ layout-card.js:1
updated @ layout-card.js:1
performUpdate @ updating-element.ts:720
_enqueueUpdate @ updating-element.ts:653
async function (async)
_enqueueUpdate @ updating-element.ts:640
_requestUpdate @ updating-element.ts:605
set @ updating-element.ts:313
value @ hui-panel-view.ts:36
performUpdate @ updating-element.ts:704
_enqueueUpdate @ updating-element.ts:653
async function (async)
_enqueueUpdate @ updating-element.ts:640
_requestUpdate @ updating-element.ts:605
set @ updating-element.ts:313
value @ hui-root.ts:463
performUpdate @ updating-element.ts:720
_enqueueUpdate @ updating-element.ts:653
async function (async)
_enqueueUpdate @ updating-element.ts:640
_requestUpdate @ updating-element.ts:605
set @ updating-element.ts:313
commit @ parts.ts:420
commit @ parts.ts:133
update @ template-instance.ts:53
__commitTemplateResult @ parts.ts:268
commit @ parts.ts:218
s @ render.ts:55
V.render @ shady-render.ts:277
update @ lit-element.ts:220
performUpdate @ updating-element.ts:704
_enqueueUpdate @ updating-element.ts:653
async function (async)
_enqueueUpdate @ updating-element.ts:640
_requestUpdate @ updating-element.ts:605
set @ updating-element.ts:313
value @ partial-panel-resolver.ts:132
value @ hass-router-page.ts:84
performUpdate @ updating-element.ts:704
_enqueueUpdate @ updating-element.ts:653
async function (async)
_enqueueUpdate @ updating-element.ts:640
_requestUpdate @ updating-element.ts:605
set @ updating-element.ts:313
commit @ parts.ts:420
commit @ parts.ts:133
update @ template-instance.ts:53
__commitTemplateResult @ parts.ts:268
commit @ parts.ts:218
s @ render.ts:55
V.render @ shady-render.ts:277
update @ lit-element.ts:220
performUpdate @ updating-element.ts:704
_enqueueUpdate @ updating-element.ts:653
async function (async)
_enqueueUpdate @ updating-element.ts:640
_requestUpdate @ updating-element.ts:605
set @ updating-element.ts:313
commit @ parts.ts:420
commit @ parts.ts:133
update @ template-instance.ts:53
__commitTemplateResult @ parts.ts:268
commit @ parts.ts:218
update @ template-instance.ts:53
__commitTemplateResult @ parts.ts:268
commit @ parts.ts:218
s @ render.ts:55
V.render @ shady-render.ts:277
update @ lit-element.ts:220
performUpdate @ updating-element.ts:704
_enqueueUpdate @ updating-element.ts:653
async function (async)
_enqueueUpdate @ updating-element.ts:640
_requestUpdate @ updating-element.ts:605
set @ updating-element.ts:313
value @ hass-base-mixin.ts:49
(anonymous) @ connection-mixin.ts:140
n @ store.ts:40
(anonymous) @ entities.ts:13
(anonymous) @ entities.ts:7
c._handleMessage @ connection.ts:254
(anonymous) @ connection.ts:100
slider-entity-row.js:20 Uncaught (in promise) TypeError: Cannot read property 'state' of null
    at HTMLElement.render (slider-entity-row.js:20)
    at HTMLElement.update (lit-element.ts:217)
    at HTMLElement.performUpdate (updating-element.ts:704)
    at HTMLElement._enqueueUpdate (updating-element.ts:653)
render @ slider-entity-row.js:20
update @ lit-element.ts:217
performUpdate @ updating-element.ts:704
_enqueueUpdate @ updating-element.ts:653
async function (async)
_enqueueUpdate @ updating-element.ts:640
_requestUpdate @ updating-element.ts:605
set @ updating-element.ts:313
(anonymous) @ vertical-stack-in-card.js:110
set hass @ vertical-stack-in-card.js:109
updated @ state-switch.js:1
performUpdate @ updating-element.ts:720
_enqueueUpdate @ updating-element.ts:653
async function (async)
_enqueueUpdate @ updating-element.ts:640
_requestUpdate @ updating-element.ts:605
set @ updating-element.ts:313
(anonymous) @ vertical-stack-in-card.js:110
set hass @ vertical-stack-in-card.js:109
(anonymous) @ layout-card.js:1
updated @ layout-card.js:1
performUpdate @ updating-element.ts:720
_enqueueUpdate @ updating-element.ts:653
async function (async)
_enqueueUpdate @ updating-element.ts:640
_requestUpdate @ updating-element.ts:605
set @ updating-element.ts:313
value @ hui-panel-view.ts:36
performUpdate @ updating-element.ts:704
_enqueueUpdate @ updating-element.ts:653
async function (async)
_enqueueUpdate @ updating-element.ts:640
_requestUpdate @ updating-element.ts:605
set @ updating-element.ts:313
value @ hui-root.ts:463
performUpdate @ updating-element.ts:720
_enqueueUpdate @ updating-element.ts:653
async function (async)
_enqueueUpdate @ updating-element.ts:640
_requestUpdate @ updating-element.ts:605
set @ updating-element.ts:313
commit @ parts.ts:420
commit @ parts.ts:133
update @ template-instance.ts:53
__commitTemplateResult @ parts.ts:268
commit @ parts.ts:218
s @ render.ts:55
V.render @ shady-render.ts:277
update @ lit-element.ts:220
performUpdate @ updating-element.ts:704
_enqueueUpdate @ updating-element.ts:653
async function (async)
_enqueueUpdate @ updating-element.ts:640
_requestUpdate @ updating-element.ts:605
set @ updating-element.ts:313
value @ partial-panel-resolver.ts:132
value @ hass-router-page.ts:84
performUpdate @ updating-element.ts:704
_enqueueUpdate @ updating-element.ts:653
async function (async)
_enqueueUpdate @ updating-element.ts:640
_requestUpdate @ updating-element.ts:605
set @ updating-element.ts:313
commit @ parts.ts:420
commit @ parts.ts:133
update @ template-instance.ts:53
__commitTemplateResult @ parts.ts:268
commit @ parts.ts:218
s @ render.ts:55
V.render @ shady-render.ts:277
update @ lit-element.ts:220
performUpdate @ updating-element.ts:704
_enqueueUpdate @ updating-element.ts:653
async function (async)
_enqueueUpdate @ updating-element.ts:640
_requestUpdate @ updating-element.ts:605
set @ updating-element.ts:313
commit @ parts.ts:420
commit @ parts.ts:133
update @ template-instance.ts:53
__commitTemplateResult @ parts.ts:268
commit @ parts.ts:218
update @ template-instance.ts:53
__commitTemplateResult @ parts.ts:268
commit @ parts.ts:218
s @ render.ts:55
V.render @ shady-render.ts:277
update @ lit-element.ts:220
performUpdate @ updating-element.ts:704
_enqueueUpdate @ updating-element.ts:653
async function (async)
_enqueueUpdate @ updating-element.ts:640
_requestUpdate @ updating-element.ts:605
set @ updating-element.ts:313
value @ hass-base-mixin.ts:49
(anonymous) @ connection-mixin.ts:140
n @ store.ts:40
(anonymous) @ entities.ts:13
(anonymous) @ entities.ts:7
c._handleMessage @ connection.ts:254
(anonymous) @ connection.ts:100

**Comment by gadgetchnnel** [comment]
@J-Lindvig 
```
fetch-with-auth.ts:20 POST https://ha.skovtrolden.duckdns.org/api/template 401
```
That should only appear if you are on 0.0.7 or earlier. If you use HACS, do the following:

* Go to HACS > Installed > Lovelace Card Templater (under Plugins)
* Click on the 3 dots menu in the top right hand corner

It should look something like this:

![image](https://user-images.githubusercontent.com/2099542/74632562-8abf0300-5157-11ea-8671-63bc91aef400.png)

* If it says "Show beta" rather than "Hide beta" then click on the "Show beta" link.
* If the installed version shows as other than 0.0.8b1 then select 0.0.8b1 from the releases dropdown and click Update
* If it was showing 0.0.8b1 click up Reinstall to force it to re-download that version

**Comment by J-Lindvig** [comment]
Thank you for your time and rapid reply.

By installing the beta, resetting user from administrator to user, the error returned.

Any other steps for me to do in helping you rectify this matter?

/Jacob

Den 17. februar 2020 08.35.43 CET, Steven Rollason <notifications@github.com> skrev:
>@J-Lindvig 
>```
>fetch-with-auth.ts:20 POST
>https://ha.skovtrolden.duckdns.org/api/template 401
>```
>That should only appear if you are on 0.0.7 or earlier. If you use
>HACS, do the following:
>
>* Go to HACS > Installed > Lovelace Card Templater (under Plugins)
>* Click on the 3 dots menu in the top right hand corner
>
>It should look something like this:
>
>![image](https://user-images.githubusercontent.com/2099542/74632562-8abf0300-5157-11ea-8671-63bc91aef400.png)
>
>* If it says "Show beta" rather than "Hide beta" then click on the
>"Show beta" link.
>* If the installed version shows as other than 0.0.8b1 then select
>0.0.8b1 from the releases dropdown and click Update
>* If it was showing 0.0.8b1 click up Reinstall to force it to
>re-download that version
>
>
>
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/gadgetchnnel/lovelace-card-templater/issues/11#issuecomment-586854902

-- 
Dette er sendt fra min mobiltelefon. Undskyld at jeg fatter mig i korthed.

**Comment by gadgetchnnel** [comment]
@J-Lindvig Can you try updating to the latest beta (0.0.8b2)?
This doesn't actually contain any updates to the templating code, but it does include some additional logging on startup to make it more obvious if you have the correct version. After updating and refreshing the page, you should see the following in the Javascript console if you have the latest version:

![Screenshot 2020-02-17 at 16 35 40](https://user-images.githubusercontent.com/2099542/74671779-d26b7c00-51a3-11ea-9f9b-264951ce10d9.png)

If you don't see this try doing a hard reload with Ctrl+Reload button or Ctrl+F5 (or if you have the Chrome Developer Tools open you can hold down on the Reload button and select "Empty Cache and Hard Reload" to be certain).

**Comment by gadgetchnnel** [comment]
Closing as stale, please raise another issue if this is still a problem.
