### ISSUE TITLE
Release tags to match custom_card.json

### ISSUE THREAD

**Issue by alexander-bauer** [gadgetchnnel/lovelace-card-templater#3]
Hello!

I currently use Git submodules to manage my custom card dependencies, and prefer to use Git version/release tags to refer to specific commits in repositories. I notice that there are version numbers in the `custom_card.json` for use with `custom_updater`, but not Git tags to match.

Would you be willing to add these?

Best,
Sasha

**Comment by gadgetchnnel** [comment]
Thanks for reminding me about this, I had been meaning to get around to this. I've now added them.

**Comment by alexander-bauer** [comment]
Thanks so much!
