### ISSUE TITLE
Custom element doesn't exist

### ISSUE THREAD

**Issue by B0ndo2** [gadgetchnnel/lovelace-card-templater#34]
I am getting this error "Custom element doesn't exist: card-templater.". 
I installed the code using HACS, resource is shown

/hacsfiles/lovelace-card-templater/lovelace-card-templater.js      JavaScript Module

type: 'custom:card-templater'
card:
  type: picture-entity
  name_template: '{{ states.sensor.recycling.attributes.days }} days'
  show_name: true
  show_state: false
  entity: sensor.recycling
  state_image:
    '0': /local/containers/bio_today.png
    '1': /local/containers/bio_tomorrow.png
    '2': /local/containers/bio_off.png
  entities:
    - sensor.recycling

**Comment by ionuttimofte53** [comment]
any somution to this? im hitting the same issue, with exact same content

**Comment by schieb** [comment]
I had the same problem. **Solved by clearing the browser cache**.

I am new to this ecosystem but based on the [required step](https://hacs.xyz/docs/configuration/basic/#clear-your-browser-cache) in the HACS installation guide, I feel like clearing your cache is just a step that needs to be added to everyone's debugging process, particularly after installing or reconfiguring any new integrations or frontends from HACS.

**Comment by gadgetchnnel** [comment]
Closing this as I believe it to be resolved - if anybody still has problems with this, please raise a new issue.
