### ISSUE TITLE
Polymer use

### ISSUE THREAD

**Issue by Anto79-ops** [gadgetchnnel/lovelace-card-templater#69]
Hi,

Does this card use Polymer or just referencing the license? For HA 2023.5

thanks

**Comment by gadgetchnnel** [comment]
Where do you see the reference to Polymer? This card uses Lit and not Polymer, so there should not be any references.

**Comment by Anto79-ops** [comment]
thanks. false alarm. I updated to beta and there's no issue. It seem the code references Polymer licenses but does not actually use Polymer. 

Edit: @gadgetchnnel for example, 

`lovelace-card-templater.js` Line 11 and beyond just mentions the word Polymer
