### ISSUE TITLE
Please add a user variable

### ISSUE THREAD

**Issue by i00** [gadgetchnnel/lovelace-card-templater#8]
Can you please expose the hass.user as a variable we can use in the templates? this would allow us to change things based on the logged in user

Thanks :)

**Comment by gadgetchnnel** [comment]
@i00 This has now been added in the latest beta (0.0.6b3). This adds the following variables for use in templates:

- user.name - the name of the current user
- user.is_admin - whether the current user is an admin
- user.is_owner - whether the current user is the owner
- page.path - the path name of the current page (e.g. /lovelace/home)

**Comment by gadgetchnnel** [comment]
Closing this as this feature is now in the non-beta release
