### ISSUE TITLE
Fills in the entities set in the custom:card-templater rather than what I set under card:

### ISSUE THREAD

**Issue by i00** [gadgetchnnel/lovelace-card-templater#9]
Fills in the entities set in the custom:card-templater rather than what I set under card e.g:
![image](https://user-images.githubusercontent.com/1435262/71954867-699ef480-3232-11ea-8cb4-cc30c9ff033c.png)

**Comment by gadgetchnnel** [comment]
Can you please post your card config as text rather than an image? This will make it easier for me to try to reproduce your issue.

**Comment by gadgetchnnel** [comment]
@i00 I've fixed this in the latest beta 0.0.6b3

**Comment by gadgetchnnel** [comment]
Closing this as the fix is now in the non-beta release
